version: 2.1
jobs:
  Test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: npm i
          command: |
            ls -al
            npm i
      - run:
          name: Running tests
          command: |
            npm run test
  Readme:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: npm i
          command: |
            npm i
      - run:
          name: npm build:README
          command: |
            npm run build:README
  Release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - Test
      - Release:
          requires:
            - Test
          filters:
            branches:
              only: master
      - Readme:
          requires:
            - Release
          filters:
            branches:
              only: master
