version: 2.1
jobs:
  Test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: npm i
          command: |
            ls -al
            npm i
      - run:
          name: Running tests
          command: |
            npm run test
  Release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npx semantic-release
      - run: npm run deploy:storybook -- --ci --host-token-env-variable=GITHUB_TOKEN

workflows:
  version: 2
  Default:
    jobs:
      - Test
      - Release:
          requires:
            - Test
          filters:
            branches:
              only: master
